name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "focal"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "RK3318 BOX"                   # build target
          armbian_minimal:   "no"
          armbian_desktop:   "yes"
          armbian_expert:    "yes"
